--- 

# This file will download files needed for the install of Splunk
# 
# This is seperate from the main splunk_cluster project. This is specifically geared to the Vagrant Splunk install.
#
# The get_url will only download if the file does not exist already.
- hosts: ansiblemaster
  become: yes
  become_method: sudo
 
  tasks:

  - name: Download Splunk Enterprise
    get_url:
      url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=6.6.1&product=splunk&filename=splunk-6.6.1-aeae3fe0c5af-Linux-x86_64.tgz&wget=true
      dest: /tmp/shared
      mode: 0440

  - name: Download Splunk Universal Forwarder (Linux)
    get_url:
      url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=6.6.1&product=universalforwarder&filename=splunkforwarder-6.6.1-aeae3fe0c5af-Linux-x86_64.tgz&wget=true
      dest: /tmp/shared
      mode: 0440

#- name: Add a cron job to run the main splunk_cluster/site.yml file
#  cron: